create table profiles (
    id bigint generated by default as identity,
    biography varchar(500),
    name varchar(255),
    url varchar(255),
    primary key (id)
);

create table films (
    id bigint generated by default as identity,
    avg_rating float(53),
    description varchar(500),
    genre varchar(255) check (genre in ('ACTION','ADVENTURE','ANIMATION','COMEDY','CRIME','DOCUMENTARY','DRAMA','FAMILY','FANTASY','HISTORY','HORROR','MUSIC','MYSTERY','ROMANCE','SCIENCE','FICTION','THRILLER','TV','MOVIE','WAR','WESTERN')),
    like_count bigint,
    list_count bigint,
    release_date date,
    running_time_minutes integer,
    title varchar(255),
    url varchar(255),
    watched_count bigint,
    director_id bigint,
    primary key (id),
    foreign key (director_id) references profiles (id),
    constraint uc_films unique (url)
);

create table film_cast (
    film_id bigint not null,
    profile_id bigint not null,
    primary key (film_id, profile_id),
    foreign key (film_id) references films (id),
    foreign key (profile_id) references profiles (id)
);

create table activity_on_film (
    film_id bigint not null,
    user_id bigint not null,
    is_in_watchlist boolean,
    is_liked boolean,
    is_watched boolean,
    rating float(53),
    watchlist_add_date date,
    primary key (film_id, user_id)
);

create table reviews (
    id bigint generated by default as identity,
    comment_ids bigint array,
    contains_spoilers boolean,
    content varchar(255),
    creation_date date,
    film_id bigint,
    is_liked boolean,
    liked_users_ids bigint array,
    rating float(53),
    user_id bigint,
    watched_on_date date,
    watched_this_film_before boolean,
    primary key (id)
);

create table users (
    id bigint generated by default as identity,
    email varchar(255),
    password varchar(255) not null,
    role smallint check (role between 0 and 1),
    username varchar(255) not null,
    primary key (id),
    constraint uc_users unique (username, email)
);